# Generated by Django 2.0.4 on 2018-05-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='account',
            name='asset_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.AssetType'),
        ),
    ]
