# Generated by Django 2.0.4 on 2018-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180509_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
    ]
