# Generated by Django 2.0.5 on 2018-05-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180509_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='posted',
            new_name='authorised',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='action',
        ),
        migrations.AddField(
            model_name='journal',
            name='credit_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='debit_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='accounts.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Purchase'), (1, 'Expense'), (2, 'Asset'), (3, 'Revenue'), (4, 'Liability'), (5, 'Equity'), (6, 'Contra-Asset')]),
        ),
    ]
